baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  # Enable to show reading time in minutes for posts
  showReadingTime = false

  homeSubtitle = "Calvin University Computer Science Club"

[languages]
  [languages.en]
    title = "Abstraction"
    keywords = ""
    copyright = "The Calvin Abstraction Club is an official student organization of Calvin College serving Calvin students interested in computer science.<a href='http://eepurl.com/hpV8xz'>Mailing List</a>"
    menuMore = "..."
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
    #  logoText = "Calvin Abstraction"
      logoHomeLink = "/"
    # or
    #
      path = "/img/abs-logo.svg"
      alt = "Calvin Abstraction"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        weight = 1
        url = "/about"

      # [[languages.en.menu.main]]
      #   identifier = "Leadership"
      #   name = "Leadership"
      #   weight = 2
      #   url = "/leadership"

       [[languages.en.menu.main]]
        identifier = "Archive"
        name = "Blog"
        weight = 3
        url = "/blog"

      [[languages.en.menu.main]]
        identifier = "Leadership"
        name = "Leadership"
        weight = 4
        url = "/leadership"
