name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    environment: test
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes
          fetch-depth: 0

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.64.0"

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --minify

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.PROXY_USERNAME }}
          proxy_key: ${{ secrets.PROXY_PRIV_KEY }}
          # key: ${{ secrets.PRIV_KEY }}
          source: "tests/a.txt,tests/b.txt"
          target: "test"
        # shell: bash
        # with:
        #   env: 
        #     FOO: ${{ github.sha }}
        #   password: ${{ secrets.ACCESS_TOKEN }}
        #   run: |
        #     echo $PATH
        #     chmod +x "${GITHUB_WORKSPACE}/.github/abs-deploy.sh"

        #     # run script
        #     "${GITHUB_WORKSPACE"/.github/abs-deploy.sh"
